# Generated by Django 4.2.4 on 2023-12-27 17:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confg', models.CharField(max_length=100, verbose_name='Confg')),
                ('image1', models.CharField(blank=True, max_length=100, null=True, verbose_name='1. Resim linki')),
                ('image2', models.CharField(blank=True, max_length=100, null=True, verbose_name='2. Resim linki')),
                ('image3', models.CharField(blank=True, max_length=100, null=True, verbose_name='3. Resim linki')),
                ('image4', models.CharField(blank=True, max_length=100, null=True, verbose_name='4. Resim linki')),
                ('image5', models.CharField(blank=True, max_length=100, null=True, verbose_name='5. Resim linki')),
                ('image6', models.CharField(blank=True, max_length=100, null=True, verbose_name='6. Resim linki')),
            ],
        ),
        migrations.CreateModel(
            name='announcments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcments_url', models.CharField(max_length=200, verbose_name='Duyuru URL adı')),
                ('title', models.CharField(max_length=200, verbose_name='Duyuru Başlığı')),
                ('message', models.CharField(max_length=50, verbose_name='Kısa mesaj')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Duyuru İçeriği')),
                ('image', models.CharField(max_length=100, verbose_name='Resim linki')),
            ],
        ),
        migrations.CreateModel(
            name='galeri_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.IntegerField(max_length=100, verbose_name='Gösterim Sırası')),
                ('image1', models.CharField(max_length=100, verbose_name='1. Resim linki')),
                ('image2', models.CharField(max_length=100, verbose_name='2. Resim linki')),
                ('image3', models.CharField(max_length=100, verbose_name='3. Resim linki')),
            ],
        ),
        migrations.CreateModel(
            name='project_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_url', models.CharField(max_length=200, verbose_name='Proje URL adı')),
                ('title', models.CharField(max_length=200, verbose_name='Proje Başlığı')),
                ('date', models.CharField(max_length=100, verbose_name='Proje Tarihi')),
                ('referans', models.CharField(max_length=100, verbose_name='Proje Referansı')),
                ('hedef', models.CharField(max_length=100, verbose_name='Hedef Kitle')),
                ('butce', models.CharField(max_length=100, verbose_name='Proje Bütçesi')),
                ('partner', ckeditor.fields.RichTextField(verbose_name='Proje Partnerleri')),
                ('akis', ckeditor.fields.RichTextField(verbose_name='Proje Akışı')),
                ('aciklama', ckeditor.fields.RichTextField(verbose_name='Proje Açıklaması')),
                ('image1', models.CharField(blank=True, max_length=100, null=True, verbose_name='1. resim linki')),
                ('image1text', models.CharField(blank=True, max_length=100, null=True, verbose_name='1. resim info')),
                ('image2', models.CharField(blank=True, max_length=100, null=True, verbose_name='2. resim linki')),
                ('image2text', models.CharField(blank=True, max_length=100, null=True, verbose_name='2. resim info')),
                ('image3', models.CharField(blank=True, max_length=100, null=True, verbose_name='3. resim linki')),
                ('image3text', models.CharField(blank=True, max_length=100, null=True, verbose_name='3. resim info')),
                ('image4', models.CharField(blank=True, max_length=100, null=True, verbose_name='4. resim linki')),
                ('image4text', models.CharField(blank=True, max_length=100, null=True, verbose_name='4. resim info')),
                ('image5', models.CharField(blank=True, max_length=100, null=True, verbose_name='5. resim linki')),
                ('image5text', models.CharField(blank=True, max_length=100, null=True, verbose_name='5. resim info')),
                ('image6', models.CharField(blank=True, max_length=100, null=True, verbose_name='6. rsim linki')),
                ('image6text', models.CharField(blank=True, max_length=100, null=True, verbose_name='6. resim info')),
                ('image7', models.CharField(blank=True, max_length=100, null=True, verbose_name='7. resim linki')),
                ('image7text', models.CharField(blank=True, max_length=100, null=True, verbose_name='7. resim info')),
                ('image8', models.CharField(blank=True, max_length=100, null=True, verbose_name='8. resim linki')),
                ('image8text', models.CharField(blank=True, max_length=100, null=True, verbose_name='8. resim info')),
                ('image9', models.CharField(blank=True, max_length=100, null=True, verbose_name='9. resim linki')),
                ('image9text', models.CharField(blank=True, max_length=100, null=True, verbose_name='9. resim info')),
            ],
        ),
    ]
