# Generated by Django 4.2.4 on 2024-02-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeri_page',
            name='display',
            field=models.IntegerField(verbose_name='Gösterim\xa0Sırası'),
        ),
    ]
